name: Streamlit Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libsqlite3-dev wget
        wget https://www.sqlite.org/2024/sqlite-autoconf-3400100.tar.gz
        tar xvfz sqlite-autoconf-3400100.tar.gz
        cd sqlite-autoconf-3400100
        ./configure --prefix=/usr/local
        make
        sudo make install
        sqlite3 --version

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Streamlit
      run: |
        streamlit run app.py
